version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: sentimental_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: B@yen1@$$e
      MYSQL_DATABASE: rencontre_sentimental
      MYSQL_USER: sentimental_user
      MYSQL_PASSWORD: sentimental_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/rencontre_sentimental.sql:/docker-entrypoint-initdb.d/init.sql

  php:
    image: rencontre-sentimental-php
    container_name: sentimental_php
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
      - ./uploads:/var/www/html/uploads

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sentimental_pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: B@yen1@$$e
    depends_on:
      - db

volumes:
  db_data: